name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows EXE
        run: npm run build-win

      - name: Upload Portable EXE
        uses: actions/upload-artifact@v4
        with:
          name: SUOMSIANGCRYPTO-MUSIC-Portable
          path: dist/*Portable*.exe

      - name: Upload Installer EXE
        uses: actions/upload-artifact@v4
        with:
          name: SUOMSIANGCRYPTO-MUSIC-Installer
          path: dist/*Setup*.exe
